export const categories = [
  'Transporte y Logística',
  'Construcción e Infraestructura',
  'Seguridad y Defensa',
  'Fuerzas Armadas',
  'Comunicación y Marketing',
  'Turismo y Hostelería',
  'Arte, Cultura y Entretenimiento',
  'Administración Pública y Gobierno',
  'Finanzas, Contabilidad y Negocios',
  'Tecnología de la Información',
  'Educación y Formación',
  'Salud y Medicina',
  'Energía y Minería',
  'Manufactura y Producción',
  'Agricultura y Desarrollo Rural',
  'Matemáticas y Estadística',
  'Ciencias Naturales y Medio Ambiente',
  'Ciencias e Investigación',
  'Gerencia y Administración de Propiedades',
  'Atención al Cliente y Ventas',
  'Liderazgo y Organizaciones Sociales',
  'Otros',
];
